<a href="https://colab.research.google.com/github/nourloca1013-jpg/Student_Id-Library.project/blob/main/Student_Id_Library_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Name: Malak Mohammed Ragaey***

# ***Task 1:***
Part 1:

In [1]:
import numpy as np
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect("/content/library.db.db")

In [3]:
# Question 1:
print("Answer of question 1:")
q1 = """SELECT member_id, COUNT(*)
FROM checkouts
GROUP BY member_id;"""
pd.read_sql_query(q1, conn)

Answer of question 1:

    member_id  COUNT(*)
0        1001         1
1        1002         2
2        1003         9
3        1005         3
4        1006         1
..        ...       ...
57       1075         9
58       1076         7
59       1077         6
60       1079        10
61       1080         2

[62 rows x 2 columns]

In [4]:
# Question 2:
print("Answer of question 2:")
q2 = """SELECT *
FROM books
WHERE author LIKE 'A%';"""
pd.read_sql_query(q2, conn)

Answer of question 2:

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez
5      506  The Paper Boat Club      Aya Hafez

In [5]:
# Question 3:
print("Answer of question 3:")
q3 = """SELECT book_id, COUNT(*)
FROM checkouts
GROUP BY book_id
ORDER BY COUNT(*) DESC LIMIT 5;"""
pd.read_sql_query(q3, conn)

Answer of question 3:

   book_id  COUNT(*)
0      501        57
1      507        55
2      513        46
3      519        38
4      525        25

In [6]:
# Question 4:
print("Answer of question 4:")
q4 = """SELECT member_id, COUNT(*)
FROM checkouts
GROUP BY member_id
ORDER BY COUNT(*) DESC LIMIT 10;"""
pd.read_sql_query(q4, conn)

Answer of question 4:

   member_id  COUNT(*)
0       1034        25
1       1044        21
2       1008        19
3       1027        18
4       1010        18
5       1065        17
6       1024        17
7       1018        17
8       1047        16
9       1030        16

In [7]:
# Question 5:
print("Answer of question 5:")
q5 = """SELECT member_id, COUNT(*)
FROM checkouts
GROUP BY member_id
ORDER BY COUNT(*) ASC LIMIT 10;"""
pd.read_sql_query(q5, conn)

Answer of question 5:

   member_id  COUNT(*)
0       1001         1
1       1006         1
2       1009         1
3       1014         1
4       1023         1
5       1031         1
6       1035         1
7       1036         1
8       1046         1
9       1049         1

Part 2:

In [8]:
query = "SELECT * FROM checkouts, members, books WHERE checkouts.member_id = members.member_id AND checkouts.book_id = books.book_id"
final_df = pd.read_sql(query, conn)

final_df.to_csv("Task1_combined_data.csv", index=False)

# ***Task 2:***

In [9]:
df = pd.read_csv("/content/Task1_combined_data.csv")

In [10]:
print("Shape of the data:", df.shape)

Shape of the data: (391, 15)

In [11]:
print("Data info:", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   checkout_id        391 non-null    int64
 1   member_id          391 non-null    int64
 2   book_id            391 non-null    int64
 3   checkout_date      391 non-null    object
 4   return_date        326 non-null    object
 5   member_id.1        391 non-null    int64
 6   first_name         391 non-null    object
 7   last_name          391 non-null    object
 8   grade              355 non-null    float64
 9   neighborhood       391 non-null    object
 10  membership_status  391 non-null    object
 11  join_date          386 non-null    object
 12  book_id.1          391 non-null    int64
 13  title              391 non-null    object
 14  author             391 non-null    object
dtypes: float64(1), int64(5), object(9)
memory usage: 45.9+ KB
Data info: None

In [12]:
print("Number of null cells before dealing with them:", df.isna().sum())

Number of null cells before dealing with them: checkout_id           0
member_id             0
book_id               0
checkout_date         0
return_date          65
member_id.1           0
first_name            0
last_name             0
grade                36
neighborhood          0
membership_status     0
join_date             5
book_id.1             0
title                 0
author                0
dtype: int64

In [13]:
df['return_date'] = df['return_date'].fillna('Not returned yet')

In [14]:
df['grade'] = df['grade'].fillna('Unknown grade')

In [15]:
df['join_date'] = df['join_date'].fillna('Unknown joining date')

In [16]:
print("Number of null cells after dealing with them:", df.isna().sum())

Number of null cells after dealing with them: checkout_id          0
member_id            0
book_id              0
checkout_date        0
return_date          0
member_id.1          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
book_id.1            0
title                0
author               0
dtype: int64

In [17]:
print("Number of duplicated rows:", df.duplicated().sum())

Number of duplicated rows: 8

In [18]:
df = df.drop_duplicates()

In [19]:
print("Shape of data after removing duplicates:", df.shape)

Shape of data after removing duplicates: (383, 15)

In [20]:
df["membership_status"] = df["membership_status"].str.strip()

In [21]:
df["membership_status"] = df["membership_status"].str.title()

In [22]:
df["neighborhood"] = df["neighborhood"].str.strip()

In [23]:
df["neighborhood"] = df["neighborhood"].str.title()

In [24]:
print(df['grade'].value_counts())

grade
9.0              105
7.0               82
8.0               80
6.0               80
Unknown grade     36
Name: count, dtype: int64

In [25]:
print(df[df['return_date'] < df['checkout_date']])

Empty DataFrame
Columns: [checkout_id, member_id, book_id, checkout_date, return_date, member_id.1, first_name, last_name, grade, neighborhood, membership_status, join_date, book_id.1, title, author]
Index: []

In [26]:
df.to_csv("Task2_cleaned_data.csv", index=False)

# Data cleaning report:

1- Dealing with missing values: Missing values in return dates were replaced with "Not returned yet" and missing values in grades and join dates were replaced with "Unknown".

2- Dealing with duplicates: 8 duplicated rows were found and dropped.

3- Text formatting: Extra spaces were cleaned using strip() function and the text in neighborhood and membership_status was edited to be the same thing using strip() and title().

4- Data integrity: Grades, checkout and return dates were verified that they are valid and logical.

# ***Task 3: ***

In [27]:
df_cleaned = pd.read_csv("/content/Task2_cleaned_data.csv")

In [29]:
print("Checkouts per neighborhood:")
print(df['neighborhood'].value_counts())

Checkouts per neighborhood:
neighborhood
Maadi         106
Nasr City      97
Heliopolis     84
Zamalek        62
Shubra         34
Name: count, dtype: int64