<a href="https://colab.research.google.com/github/nourloca1013-jpg/Student_Id-Library.project/blob/main/Student_Id_Library_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Task 1:***
Part 1:

In [18]:
import numpy as np
import pandas as pd
import sqlite3 as sql

In [19]:
conn = sql.connect("/content/library.db.db")

In [20]:
# Question 1:
q1 = """SELECT member_id, COUNT(*)
FROM checkouts
GROUP BY member_id;"""
pd.read_sql_query(q1, conn)

    member_id  COUNT(*)
0        1001         1
1        1002         2
2        1003         9
3        1005         3
4        1006         1
..        ...       ...
57       1075         9
58       1076         7
59       1077         6
60       1079        10
61       1080         2

[62 rows x 2 columns]

In [21]:
# Question 2:
q2 = """SELECT *
FROM books
WHERE author LIKE 'A%';"""
pd.read_sql_query(q2, conn)

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez
5      506  The Paper Boat Club      Aya Hafez

In [22]:
# Question 3:
q3 = """SELECT book_id, COUNT(*)
FROM checkouts
GROUP BY book_id
ORDER BY COUNT(*) DESC LIMIT 5;"""
pd.read_sql_query(q3, conn)

   book_id  COUNT(*)
0      501        57
1      507        55
2      513        46
3      519        38
4      525        25

In [23]:
# Question 4:
q4 = """SELECT member_id, COUNT(*)
FROM checkouts
GROUP BY member_id
ORDER BY COUNT(*) DESC LIMIT 10;"""
pd.read_sql_query(q4, conn)

   member_id  COUNT(*)
0       1034        25
1       1044        21
2       1008        19
3       1027        18
4       1010        18
5       1065        17
6       1024        17
7       1018        17
8       1047        16
9       1030        16

In [24]:
# Question 5:
q5 = """SELECT member_id, COUNT(*)
FROM checkouts
GROUP BY member_id
ORDER BY COUNT(*) ASC LIMIT 10;"""
pd.read_sql_query(q5, conn)

   member_id  COUNT(*)
0       1001         1
1       1006         1
2       1009         1
3       1014         1
4       1023         1
5       1031         1
6       1035         1
7       1036         1
8       1046         1
9       1049         1

Part 2:

In [25]:
query = "SELECT * FROM checkouts, members, books WHERE checkouts.member_id = members.member_id AND checkouts.book_id = books.book_id"
final_df = pd.read_sql(query, conn)

final_df.to_csv("Task1_combined_data.csv", index=False)